<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.7" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DataGridView.Services.Contracts\DataGridView.Services.Contracts.csproj" />
      <ProjectReference Include="..\DataGridView.Services\DataGridView.Services.csproj" />
      <ProjectReference Include="..\DataGridView.Storage.MsSql\DataGridView.Storage.MsSql.csproj" />
    </ItemGroup>

</Project>
